configs/qemu_sparc_ss10: add Linux kernel patch to fix build with gcc 7.x
This commit adds a Linux kernel patch that fixes the build of the
qemu_sparc_ss10 defconfig when used with gcc 7.x:

arch/sparc/kernel/pcic.c: In function ‘pcibios_fixup_bus’:
arch/sparc/kernel/pcic.c:647:8: error: ‘cmd’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    cmd |= PCI_COMMAND_IO;
        ^~

The patch has been submitted upstream.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
---
I don't know if we want to merge this patch in Buildroot. Indeed:

 - The defconfig doesn't use gcc 7.x currently, so the problem doesn't
   exist with the defconfig as-is.

 - This problem exists for essentially all SPARC configurations that
   have PCI support enabled.

The reason why I encountered this problem is because I'm testing
bleeding edge toolchains (based on gcc 7.x) with our Qemu defconfigs.